engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - public/**
  - test/**
  - "**.js"
  - "**.css"
  - "**.html"
exclude_paths:
- lib/**